"""empty message

Revision ID: 492015155a27
Revises: 782171827b92
Create Date: 2018-08-30 20:58:04.201044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '492015155a27'
down_revision = '782171827b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('contact_books', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact_books', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact_books', type_='foreignkey')
    op.drop_column('contact_books', 'created_by')
    op.drop_table('users')
    # ### end Alembic commands ###
