"""empty message

Revision ID: 782171827b92
Revises: 
Create Date: 2018-08-30 10:22:57.244472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782171827b92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_books')
    # ### end Alembic commands ###
